name: docker images

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        run: |
          docker build -t bobapp-back .
          docker tag bobapp-back ${{ vars.DOCKERHUB_USERNAME }}/bobapp-back:latest
          docker push ${{ vars.DOCKERHUB_USERNAME }}/bobapp-back:latest
