name: docker images

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/back
    steps:
        - uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push docker images backend
          uses: docker/build-push-action@v5
          with:
            context: ./back
            file: ./back/Dockerfile
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/bobapp-back:latest
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/front
    steps:
        - uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push docker images front end
          uses: docker/build-push-action@v5
          with:
            context: ./front
            file: ./front/Dockerfile
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/bobapp-front:latest
