name: docker images

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/back
    steps:
        - uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push docker images backend
          run: |
            docker build -t bobapp-back .
            docker tag bobapp-back ${{ vars.DOCKERHUB_USERNAME }}/bobapp-back:latest
            docker push ${{ vars.DOCKERHUB_USERNAME }}/bobapp-back:latest 
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/front
    steps:
        - uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push docker images front end
          run: |
            docker build -t bobapp-front .
            docker tag bobapp-back ${{ vars.DOCKERHUB_USERNAME }}/bobapp-front:latest
            docker push ${{ vars.DOCKERHUB_USERNAME }}/bobapp-front:latest

