# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
      - name: Build app
        run: npm ci
      - name: Install
        run: npm install
      - name: Build and run test
        run: npm run test-headless
  
  test-backend:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./back/
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests and generate Jacoco report
        run: mvn test jacoco:report
      - name: Jacoco coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: JaCoCo code coverage
          path: ./back/target/site/jacoco/
    
